####
### USE THIS CONFIG FILE TO GENERATE _site for local deployment to QA SERVER
### at http://developerportal.opadev.dol.gov
###
### use command: jekyll build --config qa_deploy.yml
###

# Site settings
title: United States Department of Labor Developer Portal
email: pulsier.michael@dol.gov
description: > # this means to ignore newlines until "baseurl:"
  Department of Labor Developer API Site
baseurl: ""
url: "https://developer.dol.gov"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
gems:
  - jekyll-redirect-from
